# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'Motherwise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Motherwise

  target 'MotherwiseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MotherwiseUITests' do
    # Pods for testing
  end

pod 'Alamofire', '~> 4.0'
pod 'SwiftyJSON'
pod 'FirebaseCore'
pod 'Firebase/Messaging'
pod 'Firebase/Database'
pod 'Firebase/Analytics'
pod 'Firebase/Storage'
pod 'IQKeyboardManagerSwift'
pod 'Toast-Swift'
pod 'Kingfisher'
pod 'YPImagePicker'
pod 'MultiSlider'
pod 'Cosmos'
pod 'SCLAlertView'
pod 'CountryPickerView'
pod 'moa'
pod 'Auk'
pod 'DynamicBlurView'
pod 'GSImageViewerController'
pod 'SwiftGifOrigin'
pod 'OneSignal', '>= 2.9.3', '< 3.0'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'DropDown'
pod 'MarqueeLabel'
pod 'YoutubePlayerView'
pod 'ASPVideoPlayer'
pod 'SDWebImage', '~> 5.0'
pod 'SJSegmentedScrollView'
#pod 'VoxeetSDK'
pod 'VoxeetUXKit', '~> 1.0'
pod 'Emoji-swift'
pod 'Smile'
pod 'ISEmojiView'

end
